version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes: 
      - "db-data:/data/db"
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: capstone-user
#     MONGO_INITDB_ROOT_PASSWORD: les_patates_sont_cuites
  mongoui:
    image: mrvautin/adminmongo
    environment:
      HOST: 0.0.0.0
      PORT: 4242
      PASSWORD: adminaufromagefondu
      CONTEXT: admin
    ports:
      - 4242:4242
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - steamApiId
      - steamAccount
      - steamPassword
#      GIN_MODE: release


volumes:
  db-data:
