version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes: 
      - db-data:/var/lib/mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongoui:
    image: mrvautin/adminmongo
    environment:
      HOST: 0.0.0.0
      PORT: 4242
      PASSWORD: 4242
      CONTEXT: admin
    ports:
      - 4242:4242
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release


volumes:
  db-data:
