version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release